a = "{:+5d}".format(43)
b = "{:+5d}".format(-43)
c = "{:=+5d}".format(43)
d = "{:=+5d}".format(-43)
e = "{:+05d}".format(43)
f = "{:+05d}".format(-43)

print("** 조합하기 **")
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)